language: elixir

sudo: false

elixir:
  - 1.6
  - 1.5
  - 1.4
  - 1.3

otp_release:
  - 20.2
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.3
      otp_release: 20.2

env: MIX_ENV=test

script:
  - mix credo --strict
  - mix coveralls.travis

notifications:
  email: false
